### ISSUE TITLE
Neo4j settings should accept empty username/password and provide default URL

### ISSUE THREAD

**Issue by DirkMahler** [rmllr/jqa-dashboard#2]
After initially starting up the dashboard the user is asked for connection details to the Neo4j server.

As the default situation will be a user running the Neo4j server which comes embedded with jQAssistant (`mvn jqassistant:server` or `jqassistant server` from the CLI) the settings should provide sensible defaults such that just "Save" can be clicked:

- URL: bolt://localhost
- Username: <empty>
- Password: <empty>

Furthermore there's a `Name` required. It should be evaluated if this is necessary and if so a default value (e.g. `My Project` can be specified).

**Comment by tmewes** [comment]
Hi @DirkMahler,

thank you very much for your proposition. If there are no values for the settings in the localStorage, default values are now displayed in the inputs so that new users can simply click on "Save".

The project name is currently used for the "Structure" and "Hotspots" visualizations and is therefore a required field. The default value for the project name is "My project".

If these fixes fit your needs, you're welcome to close this issue, otherwise please let me know if I can make any improvements to this issue. :)

Best regards
Tino

**Comment by tmewes** [comment]
Since the proposals have been implemented, I will close this issue. :)
